name: Deploy Airflow DAGs to Cloud Composer

on:
  push:
    paths:
      - "dags/**" # Trigger the workflow only when files in the 'dags' folder are changed
    branches:
      - main      # Run for changes pushed to the 'main' branch
      - develop   # Run for changes pushed to the 'develop' branch

jobs:
  deploy-dags:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_DEV }}
      COMPOSER_BUCKET_DEV: ${{ secrets.COMPOSER_BUCKET_DEV }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Step 3: Set the active GCP project
      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID_DEV }}

      # Step 4: Upload DAGs to Cloud Composer
      - name: Upload DAGs to Cloud Composer
        run: |
          gsutil -m rsync -r dags/ gs://${{ secrets.COMPOSER_BUCKET_DEV }}/dags/
