name: Deploy Airflow DAGs to Cloud Composer

on:
  push:
    paths:
      - "dags/**"
    branches:
      - main
      - develop

jobs:
  deploy-dags:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [main]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets[matrix.environment == 'dev' && 'GCP_PROJECT_ID_DEV' || 'GCP_PROJECT_ID_PROD'] }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > /tmp/key.json # Write the secret to a temp file
          gcloud auth activate-service-account --key-file=/tmp/key.json
          rm /tmp/key.json # Clean up after authentication

      - name: Validate Airflow DAGs
        run: python -m compileall dags/

      - name: Upload DAGs to Cloud Composer
        run: |
          if [ "${{ matrix.environment }}" == "dev" ]; then
            export COMPOSER_BUCKET=${{ secrets.COMPOSER_BUCKET_DEV }};
          else
            export COMPOSER_BUCKET=${{ secrets.COMPOSER_BUCKET_PROD }};
          fi
          gsutil -m rsync -r dags/ gs://${COMPOSER_BUCKET}/dags/
